### ISSUE TITLE
log file's analysis

### ISSUE THREAD

**Issue by thekingofhero** [spion06/intel_hadoop_metrics#1]
I got a file with name "var/log/intel-hadoop-metrics/cpustat".I'm not sure if this file has been compressed by gzip.How can i analyze this file?
thank you!

**Comment by spion06** [comment]
Since I was using an older version of logstash the .gz isn't added by default. Newer versions do this by default however they were not compatible with JDK6. It is in fact gzip compressed by default. You can use gzip, zcat or zgrep to get the data out. You can also disable the compression entirely using `default['intel_hadoop_metrics']['compress'] = false` when deploying. The obvious downside is much more space will be used.

**Comment by thekingofhero** [comment]
Thank you for your answer.I have got data from this file.
